### ISSUE TITLE
Make default action respect current version format

### ISSUE THREAD

**Issue by hailwood** [unger1984/npm-dependency-checker#1]
E.g. if I have a version set as `^2.25.0` the plugin will suggest `Replace with 2.28.0` and I can Alt+Enter to use `Replace with ^2.28.0` instead.

It would be awesome if we [switched up the registration of the quick fixes](https://github.com/unger1984/npm-dependency-checker/blob/main/src/main/kotlin/com/unger1984/npmdependencychecker/inspection/NpmPackagesInspection.kt#L52-L54) so if the current version starts with a `^` or a `~` we register that one last so it becomes the default recommended fix.

**Comment by unger1984** [comment]
Thanks for the feedback! I'll fix it in the next version

**Comment by unger1984** [comment]
Fixed in version 0.0.3
