### ISSUE TITLE
IDE hangs till the time package.json is analyzed

### ISSUE THREAD

**Issue by apgapg** [unger1984/npm-dependency-checker#2]
Hi,
thanks for amazing plugin.
My IDE hangs till the whole file is processed. and it take around 30 sec till that time IDE freezes.

**Comment by unger1984** [comment]
Thanks for report. The error has been fixed in version 0.1.1. Waiting for publication in the market

**Comment by apgapg** [comment]
Thanks

**Comment by apgapg** [comment]
Shall close once I check. Lets keep this open till then

**Comment by unger1984** [comment]
Version 0.1.1 of the npm-dependency-checker plugin has been approved by JetBrains and is now publicly available at the following link: https://plugins.jetbrains.com/plugin/18469-npm-dependency-checker

**Comment by apgapg** [comment]
![image](https://user-images.githubusercontent.com/13887407/193237401-99fa2160-af68-461e-a45a-5cdb7c1ecacd.png)

I am using webstorm. Does it support Java plugin?

**Comment by unger1984** [comment]
This plugin requires Java to function. I do not know how to get around this, if there are ideas - welcome to the PR

**Comment by apgapg** [comment]
Okay thanks. Well dont have any way right now. Webstorm might not support java
