### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by PwrSrg** [unger1984/npm-dependency-checker#3]
This plugin does **absolutely nothing**.

![2022-07-16_08-38-13](https://user-images.githubusercontent.com/711603/179357401-24151773-cc94-4dc2-aa59-61bb96ee2fac.jpg)

![2022-07-16_08-37-36](https://user-images.githubusercontent.com/711603/179357405-89553685-348a-47c0-a015-a330012bc632.jpg)

I was looking for something like [THIS](https://marketplace.visualstudio.com/items?itemName=pflannery.vscode-versionlens) which works **PERFECTLY**.

![2022-07-16_09-24-13](https://user-images.githubusercontent.com/711603/179358977-d5c3924a-7210-4e1d-b81f-763a83948dd1.jpg)

**Comment by MartinX3** [comment]
Same problem.
It does nothing.

I think I should delete it.

- `pnpm` contains an update checker
  - successor of yarn and npm
- intelliJ has auto completion of  dependency names and versions
- there is the `npm-check-updates` package in the npm repo

**Comment by xXBJXx** [comment]
I use WebStorm and it works 
![image](https://user-images.githubusercontent.com/32600934/215345361-9062a939-fcf6-4590-9f40-118ff884042e.png)
the package, it must be already installed of course, then update options are shown

**Comment by MartinX3** [comment]
Wasn't that a buildin standard feature of the IDE?

**Comment by xXBJXx** [comment]
The update window yes, but the orange underline comes from the plug-in
Plug-in deactivated
![image](https://user-images.githubusercontent.com/32600934/215353061-c7815cb4-bfe3-4b53-b380-7347abf763c0.png)
