### ISSUE TITLE
Incompatible with the latest version, 2023.1

### ISSUE THREAD

**Issue by m4heshd** [unger1984/npm-dependency-checker#4]
This plugin has been super helpful to me. Hope this gets updated soon. 🤞🏽

![image](https://user-images.githubusercontent.com/6711514/228342649-bf833cab-93cc-4672-9694-8d7cff61f903.png)

**Comment by unger1984** [comment]
Updated in 0.1.2 (waiting approve by JetBrains)

**Comment by m4heshd** [comment]
Perfect. Thank you. I'll keep the issue open till the update goes live.

**Comment by unger1984** [comment]
<img width="568" alt="image" src="https://user-images.githubusercontent.com/1415693/228385242-90849a4e-be4b-42db-a973-9f096c67adb9.png">

**Comment by m4heshd** [comment]
Is it published yet? I'm not seeing a new version for WebStorm. 🤔 

![image](https://user-images.githubusercontent.com/6711514/228385904-c17cf038-0582-4ea8-bfef-2b5faf5d5c15.png)

**Comment by unger1984** [comment]
WebStorm not supported

<img width="309" alt="image" src="https://user-images.githubusercontent.com/1415693/228386524-5af0b99e-cc0a-4f7f-a126-9af4bbf9ba0d.png">

**Comment by m4heshd** [comment]
Damn. How come the requirements suddenly changed? 😧 I used the plugin till today. I mean this plugin is pretty much useless outside of PHPStorm and WebStorm isn't it? I highly doubt people develop for Node on any other IDE of theirs.

**Comment by unger1984** [comment]
WebStrom not supported from version 0.1.0. As an experiment, you can try to install this version manually, but you are not sure if it will work https://github.com/unger1984/npm-dependency-checker/releases/tag/0.1.3

**Comment by unger1984** [comment]
I wrote this plugin for myself, and I work in the Ultimate version. Starting from version 0.1.0 we had to drop support for webstorm, because JetBrains tightened the requirements for plugins and plugins that require Java in their dependencies no longer work in other IDEs. If you can find a solution to get around this, I will gladly accept your PR

**Comment by unger1984** [comment]
<img width="1234" alt="image" src="https://user-images.githubusercontent.com/1415693/228388362-77201a62-4f3d-45f5-90b2-9e6c7886e5aa.png">

**Comment by m4heshd** [comment]
I see. I might have to write an alternative myself from the looks of it. Thank you for the information.

**Comment by WarningImHack3r** [comment]
@m4heshd you can take a look at [my rewrite](https://github.com/WarningImHack3r/npm-update-dependencies) if you want!

**Comment by m4heshd** [comment]
@WarningImHack3r Just tried it. Works perfectly on the latest version of the IDE. Thank you so much for pinging me.
